# Generated by Django 3.0.3 on 2020-06-25 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0001_initial'),
        ('atividades', '0001_initial'),
        ('utilizador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Concluida', models.IntegerField(default=0)),
                ('HorasInicio', models.TimeField()),
                ('HorasFim', models.TimeField()),
                ('Tipo', models.CharField(choices=[('Atividade', 'Atividade'), ('Acompanhar participantes', 'Acompanhar participante'), ('Outro', 'Outro')], max_length=24)),
                ('Origem', models.CharField(blank=True, default=None, max_length=200)),
                ('Destino', models.CharField(blank=True, default=None, max_length=200)),
                ('Grupos', models.IntegerField()),
                ('Descricao', models.TextField(blank=True)),
                ('Dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracoes.dias_DA', verbose_name='Dias:')),
                ('Nome_actividade', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade')),
                ('UtilizadorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilizador.coord')),
                ('UtilizadorID2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilizador.colab')),
            ],
            options={
                'verbose_name_plural': 'tarefa',
            },
        ),
        migrations.CreateModel(
            name='disponibilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inicio', models.TimeField()),
                ('Fim', models.TimeField()),
                ('Observacoes', models.TextField(blank=True)),
                ('Dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracoes.dias_DA', verbose_name='Dias:')),
                ('UtilizadorID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='UtilizadorID')),
            ],
        ),
    ]
