# Generated by Django 3.0.3 on 2020-06-25 15:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(db_column='Assunto', max_length=100)),
                ('descricao', models.TextField(blank=True, db_column='Descricao', null=True)),
                ('criadoem', models.DateTimeField(blank=True, db_column='CriadoEm', default=datetime.datetime.now)),
                ('is_read', models.BooleanField(blank=True, db_column='is_Read', null=True)),
                ('autorid', models.ForeignKey(blank=True, db_column='autorID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorid', to=settings.AUTH_USER_MODEL)),
                ('remetenteid', models.ForeignKey(blank=True, db_column='remetenteID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remetenteid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificacao',
            },
        ),
    ]
