CREATE TABLE `<<enumeration>>                         partidaChegada` (ID int(10) NOT NULL AUTO_INCREMENT, Penha int(10), Terminal int(10), Gambelas int(10), PRIMARY KEY (ID));
CREATE TABLE Atividade (ID int(10) NOT NULL AUTO_INCREMENT, TarefaID int(10) NOT NULL, CapacidadeMaxima int(10) NOT NULL, Duração varchar(255), PRIMARY KEY (ID));
CREATE TABLE AtividadeSessao (ID int(10) NOT NULL AUTO_INCREMENT, SessãoID int(10) NOT NULL, AtividadeID int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Campus (ID int(10) NOT NULL AUTO_INCREMENT, MenuID int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE ColaboradorHorario (ID int(10) NOT NULL AUTO_INCREMENT, PRIMARY KEY (ID));
CREATE TABLE Departamento (ID int(10) NOT NULL AUTO_INCREMENT, AtividadeID int(10) NOT NULL, `Unidade OrganicaID` int(10) NOT NULL, Nome varchar(255), PRIMARY KEY (ID));
CREATE TABLE `Dia Aberto` (ID int(10) NOT NULL AUTO_INCREMENT, UtilizadorID2 int(10) NOT NULL, UtilizadorID int(10) NOT NULL, EndereçoPaginaWeb varchar(255), EmailDiaAberto varchar(255), DataInscriçãoAtividadesInicio int(10), DataDiaAbertoInicio float NOT NULL, Ano int(10), Descrição varchar(255), DataInscriçãoAtividadesFim int(10), DataDiaAbertoFim int(10), DataPropostasAtividadesIncio int(10), DataPorpostaAtividadesFim int(10), PRIMARY KEY (ID));
CREATE TABLE Escola (ID int(10) NOT NULL AUTO_INCREMENT, Nome varchar(255), Local varchar(255), Telefone int(10) NOT NULL, Email varchar(255), PRIMARY KEY (ID));
CREATE TABLE Espaço (ID int(10) NOT NULL AUTO_INCREMENT, Nome varchar(255), Edificio varchar(255), Andar varchar(255), Gabinete varchar(255), Edificio2 varchar(255), Andar2 varchar(255), Descrição varchar(255), Discriminator varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Horario (ID int(10) NOT NULL AUTO_INCREMENT, SessãoID int(10) NOT NULL, Inicio float NOT NULL, Fim float NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Idioma (ID int(10) NOT NULL AUTO_INCREMENT, Nome varchar(255), Sigla varchar(255), PRIMARY KEY (ID));
CREATE TABLE Inscrição (ID int(10) NOT NULL AUTO_INCREMENT, UtilizadorID int(10), NrInscrição int(10) NOT NULL, Ano int(10), Local varchar(255), AreaCientifica int(10), NrAcompanhantes int(10), NrAlunos int(10), NResponsáveis int(10), Turma int(10), Discriminator varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE InscriçãoAtividade (ID int(10) NOT NULL AUTO_INCREMENT, PRIMARY KEY (ID));
CREATE TABLE InscriçãoTransporte (ID int(10) NOT NULL AUTO_INCREMENT, NrParticipantes int(10) NOT NULL, TransporteID int(10) NOT NULL, InscriçãoID int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Materiais (ID int(10) NOT NULL AUTO_INCREMENT, AtividadeID int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Menu (ID int(10) NOT NULL AUTO_INCREMENT, HorarioID int(10) NOT NULL, UtilizadorID int(10) NOT NULL, PreçoAlunos float NOT NULL, PreçoProfessores double, Tipo varchar(255), Menu int(10), PRIMARY KEY (ID));
CREATE TABLE MenuHorario (ID int(10) NOT NULL AUTO_INCREMENT, Origem int(10), Chegada int(10), HorarioID int(10) NOT NULL, TransporteID int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Notificação (ID int(10) NOT NULL AUTO_INCREMENT, Descrição varchar(255), CriadoEm varchar(255), PRIMARY KEY (ID));
CREATE TABLE Prato (ID int(10) NOT NULL AUTO_INCREMENT, InscriçãoID int(10) NOT NULL, NrAlmoçosDisponiveis int(10) NOT NULL, Prato int(10), PRIMARY KEY (ID));
CREATE TABLE Sessão (ID int(10) NOT NULL AUTO_INCREMENT, Horario int(10), NInscritos int(10) NOT NULL, Vagas int(10) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE Tarefa (ID int(10) NOT NULL AUTO_INCREMENT, UtilizadorID2 int(10) NOT NULL, UtilizadorID int(10) NOT NULL, Nome varchar(255), Concluida tinyint(1), PRIMARY KEY (ID));
CREATE TABLE Transporte (ID int(10) NOT NULL AUTO_INCREMENT, UtilizadorID int(10) NOT NULL, Tipo int(10), HorarioChegada int(10), Capacidade int(10), Identificação int(10), Capacidade2 int(10), Discriminator varchar(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE `Unidade Organica` (ID int(10) NOT NULL AUTO_INCREMENT, CampusID int(10) NOT NULL, Sigla varchar(255), PRIMARY KEY (ID));
CREATE TABLE Utilizador (ID int(10) NOT NULL AUTO_INCREMENT, InscriçãoID int(10), NotificaçãoID int(10) NOT NULL, Nome varchar(255), Email varchar(255), Telefone varchar(255), Password varchar(255), UserName varchar(255), Curso int(10), Preferencia int(10), Discriminator varchar(255) NOT NULL, PRIMARY KEY (ID));
ALTER TABLE Campus ADD CONSTRAINT FKCampus634822 FOREIGN KEY (MenuID) REFERENCES Menu (ID);
ALTER TABLE Utilizador ADD CONSTRAINT FKUtilizador595567 FOREIGN KEY (InscriçãoID) REFERENCES Inscrição (ID);
ALTER TABLE AtividadeSessao ADD CONSTRAINT FKAtividadeS174392 FOREIGN KEY (AtividadeID) REFERENCES Atividade (ID);
ALTER TABLE AtividadeSessao ADD CONSTRAINT FKAtividadeS838241 FOREIGN KEY (SessãoID) REFERENCES Sessão (ID);
ALTER TABLE Materiais ADD CONSTRAINT FKMateriais869399 FOREIGN KEY (AtividadeID) REFERENCES Atividade (ID);
ALTER TABLE `Unidade Organica` ADD CONSTRAINT `FKUnidade Or739655` FOREIGN KEY (CampusID) REFERENCES Campus (ID);
ALTER TABLE Departamento ADD CONSTRAINT FKDepartamen167815 FOREIGN KEY (AtividadeID) REFERENCES Atividade (ID);
ALTER TABLE Horario ADD CONSTRAINT FKHorario662821 FOREIGN KEY (SessãoID) REFERENCES Sessão (ID);
ALTER TABLE Menu ADD CONSTRAINT FKMenu229697 FOREIGN KEY (HorarioID) REFERENCES Horario (ID);
ALTER TABLE Departamento ADD CONSTRAINT FKDepartamen605699 FOREIGN KEY (`Unidade OrganicaID`) REFERENCES `Unidade Organica` (ID);
ALTER TABLE InscriçãoTransporte ADD CONSTRAINT FKInscriçãoT974797 FOREIGN KEY (InscriçãoID) REFERENCES Inscrição (ID);
ALTER TABLE InscriçãoTransporte ADD CONSTRAINT FKInscriçãoT337454 FOREIGN KEY (TransporteID) REFERENCES Transporte (ID);
ALTER TABLE Tarefa ADD CONSTRAINT atribui FOREIGN KEY (UtilizadorID) REFERENCES Utilizador (ID);
ALTER TABLE `Dia Aberto` ADD CONSTRAINT `consulta publicações ►` FOREIGN KEY (UtilizadorID) REFERENCES Utilizador (ID);
ALTER TABLE Transporte ADD CONSTRAINT `consulta publicações ►2` FOREIGN KEY (UtilizadorID) REFERENCES Utilizador (ID);
ALTER TABLE Menu ADD CONSTRAINT `consulta publicações ►3` FOREIGN KEY (UtilizadorID) REFERENCES Utilizador (ID);
ALTER TABLE Utilizador ADD CONSTRAINT `envia  notificação ►` FOREIGN KEY (NotificaçãoID) REFERENCES Notificação (ID);
ALTER TABLE Atividade ADD CONSTRAINT `está associada a  ►` FOREIGN KEY (TarefaID) REFERENCES Tarefa (ID);
ALTER TABLE `Dia Aberto` ADD CONSTRAINT `inscreve-se` FOREIGN KEY (UtilizadorID2) REFERENCES Utilizador (ID);
ALTER TABLE MenuHorario ADD CONSTRAINT possui FOREIGN KEY (HorarioID) REFERENCES Horario (ID);
ALTER TABLE MenuHorario ADD CONSTRAINT possui2 FOREIGN KEY (TransporteID) REFERENCES Transporte (ID);
ALTER TABLE Tarefa ADD CONSTRAINT realiza FOREIGN KEY (UtilizadorID2) REFERENCES Utilizador (ID);
ALTER TABLE Inscrição ADD CONSTRAINT realiza2 FOREIGN KEY (UtilizadorID) REFERENCES Utilizador (ID);
ALTER TABLE Prato ADD CONSTRAINT `reserva ►` FOREIGN KEY (InscriçãoID) REFERENCES Inscrição (ID);
