# Generated by Django 3.0.3 on 2020-06-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(error_messages={'unique': 'A sigla deste Curso já foi registada'}, max_length=200, unique=True, verbose_name='Sigla:')),
                ('nome', models.CharField(error_messages={'unique': 'O nome deste Curso já foi registado'}, max_length=200, unique=True, verbose_name='Nome:')),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='dias_DA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Dias do Dia Aberto',
                'db_table': 'dias_Dia_aberto',
            },
        ),
        migrations.CreateModel(
            name='escolas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(error_messages={'unique': 'Esta escola já foi registada'}, max_length=200, unique=True, verbose_name='Nome:')),
            ],
            options={
                'db_table': 'escolas',
            },
        ),
        migrations.CreateModel(
            name='horarios_atividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.IntegerField(default=0, verbose_name='Início:')),
                ('fim', models.IntegerField(default=0, verbose_name='Fim:')),
                ('periodo', models.IntegerField(default=1, verbose_name='Periodo:')),
            ],
            options={
                'verbose_name_plural': 'Horarios Atividades',
                'db_table': 'horarios_atividades',
            },
        ),
        migrations.CreateModel(
            name='horarios_transportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.IntegerField(default=0, verbose_name='Início:')),
                ('fim', models.IntegerField(default=0, verbose_name='Fim:')),
                ('periodo', models.IntegerField(default=1, verbose_name='Periodo:')),
            ],
            options={
                'verbose_name_plural': 'Horarios Transportes',
                'db_table': 'horarios_transportes',
            },
        ),
        migrations.CreateModel(
            name='horas_atividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Horas das atividades',
                'db_table': 'horas_atividades',
            },
        ),
        migrations.CreateModel(
            name='horas_transportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Horas dos transportes',
                'db_table': 'horas_transportes',
            },
        ),
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereçoPaginaWeb', models.CharField(max_length=200, verbose_name='URL:')),
                ('emailDiaAberto', models.EmailField(max_length=254, verbose_name='Email:')),
                ('ano', models.IntegerField(default=2020, error_messages={'unique': 'Já foram criadas configurações para este ano'}, unique=True, verbose_name='Ano:')),
                ('dataPropostasAtividadesIncio', models.DateField(verbose_name='Início:')),
                ('dataPorpostaAtividadesFim', models.DateField(verbose_name='Fim:')),
                ('dataInscriçãoAtividadesInicio', models.DateField(verbose_name='Início:')),
                ('dataInscriçãoAtividadesFim', models.DateField(verbose_name='Fim:')),
                ('dataDiaAbertoInicio', models.DateField(verbose_name='Início:')),
                ('dataDiaAbertoFim', models.DateField(verbose_name='Fim:')),
                ('descrição', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Configurações gerais',
                'db_table': 'configuracoes_gerais',
            },
        ),
        migrations.CreateModel(
            name='uos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(default='', error_messages={'unique': 'A sigla desta Unidade Orgânica já foi registada'}, max_length=200, unique=True, verbose_name='Sigla:')),
                ('nome', models.CharField(error_messages={'unique': 'O nome desta Unidade Orgânica já foi registado'}, max_length=200, unique=True, verbose_name='Nome:')),
            ],
            options={
                'db_table': 'uo',
            },
        ),
        migrations.CreateModel(
            name='departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(error_messages={'unique': 'O nome deste Departamento já foi registado'}, max_length=200, unique=True, verbose_name='Departamento:')),
                ('uo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracoes.uos', verbose_name='Unidade Organica:')),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
    ]
