# Generated by Django 3.0.3 on 2020-06-27 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0001_initial'),
        ('atividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='inscricao1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
                ('Tipo_de_Visitante', models.CharField(choices=[('Grupo Escolar', 'Grupo Escolar'), ('Individual', 'Individual')], max_length=50)),
                ('Nr_Pessoas', models.IntegerField()),
                ('HorarioInicio', models.CharField(max_length=100)),
                ('HorarioFim', models.CharField(max_length=100)),
                ('Precisa_Transporte', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=32, verbose_name='Precisa transporte:')),
                ('Refeicao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=32, verbose_name='Precisa transporte:')),
                ('Quantos_Alunos', models.IntegerField()),
                ('Quantos_Professores', models.IntegerField()),
                ('Escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.escolas')),
                ('UtilizadorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.dias_DA', verbose_name='Dias:')),
            ],
            options={
                'verbose_name_plural': 'inscricoes',
                'db_table': 'inscricoes',
            },
        ),
        migrations.CreateModel(
            name='inscricoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('necessitaTransporte', models.BooleanField(default=True)),
                ('entreCampus', models.BooleanField(default=False)),
                ('nParticipantes', models.IntegerField(blank=True, default=1, null=True, verbose_name='Número de participantes:')),
                ('dias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracoes.dias_DA', verbose_name='Dias:')),
                ('horaFim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaInicio', to='configuracoes.horas_transportes', verbose_name='Horas fim transportes:')),
                ('horaInicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaFim', to='configuracoes.horas_transportes', verbose_name='Horas inicio transportes:')),
            ],
            options={
                'verbose_name_plural': 'inscricoes',
                'db_table': 'inscricoes_daniel',
            },
        ),
        migrations.CreateModel(
            name='inscricao_atividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricaoID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricao1')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atividades.sessao', verbose_name='Sessao:')),
            ],
            options={
                'verbose_name_plural': 'inscricao_atividades',
                'db_table': 'inscricao_atividades_vieira',
            },
        ),
        migrations.CreateModel(
            name='atividades_inscritas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atividades.atividades', verbose_name='Atividade:')),
                ('nome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscricoes.inscricoes', verbose_name='Grupo:')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atividades.sessoes', verbose_name='Sessoes:')),
            ],
            options={
                'verbose_name_plural': 'atividades_inscritas',
                'db_table': 'atividades_inscritas_daniel',
            },
        ),
    ]
