# Generated by Django 3.0.3 on 2020-06-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao1',
            name='Quantos_Alunos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscricao1',
            name='Quantos_Professores',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
