# Generated by Django 3.0.3 on 2020-06-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricoes', '0002_auto_20200630_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao1',
            name='Observacoes',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
