# Generated by Django 3.0.3 on 2020-06-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(error_messages={'unique': 'Já foi registado um menu com este nome'}, max_length=32, unique=True, verbose_name='Nome:')),
                ('precoAluno', models.DecimalField(decimal_places=2, default='2.70', max_digits=3, verbose_name='Preço por aluno:')),
                ('precoProfessor', models.DecimalField(decimal_places=2, default='4.20', max_digits=3, verbose_name='Preço por professor:')),
                ('data', models.OneToOneField(error_messages={'unique': 'Já foi registado um menu para este dia'}, on_delete=django.db.models.deletion.CASCADE, to='configuracoes.dias_DA', verbose_name='Dias:')),
            ],
            options={
                'verbose_name_plural': 'Menu',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='ementas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sopa', models.CharField(max_length=32, verbose_name='Sopa:')),
                ('pratoCarne', models.CharField(max_length=32, verbose_name='Prato de carne:')),
                ('pratoPeixe', models.CharField(max_length=32, verbose_name='Prato de peixe:')),
                ('pratoVegetariano', models.CharField(max_length=32, verbose_name='Prato vegetariano:')),
                ('sobremesa', models.CharField(max_length=32, verbose_name='Sobremesa:')),
                ('menu', models.OneToOneField(error_messages={'unique': 'Já foi registado uma ementa para este menu'}, on_delete=django.db.models.deletion.CASCADE, to='almocos.menus', verbose_name='Menu:')),
            ],
            options={
                'verbose_name_plural': 'Ementa',
                'db_table': 'ementa',
            },
        ),
    ]
