# Generated by Django 3.0.3 on 2020-06-25 15:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='atividade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nome_actividade', models.CharField(max_length=200, unique=True)),
                ('Submetido', models.DateField(default=datetime.date.today)),
                ('Estado', models.CharField(choices=[('Pendente', 'Pendente'), ('aceite', 'Aceite'), ('rejeitado', 'Rejeitado')], default='Pendente', max_length=20)),
                ('Tipodeatividade', models.CharField(choices=[('Atividade Laboratorial', 'Atividade Laboratorial'), ('Atividades Tecnologicas', 'Atividades Tecnologicas'), ('Debate', 'Debate'), ('Palestra', 'Palestra'), ('Tertúlia', 'Tertulia')], max_length=200)),
                ('Descrição', models.CharField(max_length=20000)),
                ('Campus', models.CharField(choices=[('Gambelas', 'Gambelas'), ('Penha', 'Penha')], max_length=200)),
                ('Criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criador:')),
                ('Departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracoes.departamentos', verbose_name='Departamento:')),
                ('EntidadeOrganizacional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracoes.uos', verbose_name='UO:')),
            ],
            options={
                'verbose_name_plural': 'atividade',
                'db_table': 'atividades',
            },
        ),
        migrations.CreateModel(
            name='atividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('campus', models.CharField(choices=[('Gambelas', 'Gambelas'), ('Penha', 'Penha')], default='Gambelas', max_length=32, verbose_name='Campus:')),
                ('vagas', models.IntegerField(default='1')),
            ],
            options={
                'verbose_name_plural': 'atividades',
                'db_table': 'atividades_daniel',
            },
        ),
        migrations.CreateModel(
            name='sessoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atividades.atividades', verbose_name='Atividade:')),
                ('tempo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.horas_atividades', verbose_name='Horas atividades:')),
            ],
            options={
                'verbose_name_plural': 'sessoes',
                'db_table': 'sessoes_daniel',
            },
        ),
        migrations.CreateModel(
            name='sessao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Duraçao', models.IntegerField(default='1')),
                ('Vagas', models.IntegerField(default='1')),
                ('Espaço', models.CharField(max_length=200)),
                ('Materiais', models.CharField(max_length=20000)),
                ('Colaboradores', models.IntegerField()),
                ('Atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade', verbose_name='Atividade:')),
                ('Dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracoes.dias_DA', verbose_name='Dia:')),
                ('Inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.horas_atividades', verbose_name='Horas atividades:')),
            ],
            options={
                'verbose_name_plural': 'sessao',
                'db_table': 'sessao',
            },
        ),
    ]
