# Generated by Django 3.0.3 on 2020-06-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='autocarros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(error_messages={'unique': 'Este autocarro já foi registado'}, max_length=32, unique=True, verbose_name='Identificador do autocarro:')),
                ('capacidade', models.IntegerField(default=1, verbose_name='Capacidade máxima:')),
            ],
            options={
                'verbose_name_plural': 'Autocarros',
                'db_table': 'autocarros',
            },
        ),
        migrations.CreateModel(
            name='percursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('Faro', 'Faro'), ('Gambelas', 'Gambelas'), ('Penha', 'Penha')], default='Faro', max_length=32, verbose_name='Origem:')),
                ('destino', models.CharField(choices=[('Faro', 'Faro'), ('Gambelas', 'Gambelas'), ('Penha', 'Penha')], default='Gambelas', max_length=32, verbose_name='Destino:')),
                ('lotacao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Lotação:')),
                ('lugares_restantes', models.IntegerField(blank=True, default=10, null=True, verbose_name='Lugares restantes:')),
                ('dias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracoes.dias_DA', verbose_name='Dias:')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracoes.horas_transportes', verbose_name='Horas:')),
                ('identificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transportes.autocarros', verbose_name='ID do Autocarro:')),
            ],
            options={
                'verbose_name_plural': 'Percursos',
                'db_table': 'percursos',
            },
        ),
    ]
